openapi: 3.0.3
info:
  title: Midas Panel API
  version: 1.0.0
servers:
  - url: https://your-domain.example
paths:
  /api/health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /api/me:
    get:
      security: [ { bearerAuth: [] } ]
      summary: Current user and subscription
      responses:
        '200': { description: OK }
  /api/provision:
    post:
      security: [ { bearerAuth: [] } ]
      summary: Provision a WireGuard peer and return config + QR
      responses:
        '200': { description: OK }
  /api/stripe/webhook:
    post:
      summary: Stripe webhook
      responses: { '200': { description: OK } }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
