services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE:-midas-panel-pro:latest}
    container_name: midas-frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    depends_on:
      - postgres
      - redis
      - wg-easy

  postgres:
    image: postgres:16-alpine
    container_name: midas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-midas}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-midas}
      POSTGRES_DB: ${POSTGRES_DB:-midas}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: midas-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: midas-wg-easy
    restart: unless-stopped
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD=${WG_PASSWORD}
      - WG_DEFAULT_DNS=1.1.1.1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"

volumes:
  postgres_data:
  redis_data:
