services:
  web:
    image: node:20
    command: sh -c "corepack enable && pnpm i && pnpm dev"
    working_dir: /app
    volumes: [ ".:/app" ]
    ports: [ "3000:3000" ]
    env_file: .env
    depends_on: [ db, redis ]
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: midas
    ports: [ "5432:5432" ]
    volumes: [ "pg:/var/lib/postgresql/data" ]
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports: [ "6379:6379" ]
    volumes: [ "redis:/data" ]
volumes:
  pg:
  redis:
